### ISSUE TITLE
Need to add a Document Upload Button

### ISSUE THREAD

**Issue by RajeshTechForge** [RajeshTechForge/PINAC-Workspace#27]
**We require the addition of a button for uploading documents, specifically PDF files, inside the input box**. A sample image is shown below for reference :
![Example Screenshot](https://github.com/rmondal-official/PINAC-Workspace/assets/78198704/6576f5cf-7b4a-4e1f-a2ff-f00d406895dc)
(_Image is only for understanding purpose. Please note that the button is for PDF files and not images_)

Please let me know if you need any assistance from my end.

**Comment by DanejSakshi13** [comment]
Hi there! I've taken a look at the issue to incorporate a button for uploading PDF documents into the input box. It seems like a straightforward frontend adjustment. Could you confirm if this modification strictly involves frontend changes, with no backend adjustments required? If so, I'm ready to dive in and get it done efficiently. Thanks!

**Comment by rmondal-official** [comment]
Sure, please proceed

**Comment by rmondal-official** [comment]
Hello @DanejSakshi13, is there any problem ?

**Comment by DanejSakshi13** [comment]
Due to sudden university exams, I regretfully cannot commit to contributing to the repository. I have unsigned myself. Apologies for any inconvenience caused.

**Comment by rmondal-official** [comment]
Thank you for letting us know about your situation. University exams are definitely a priority, and we completely understand your need to focus on them. There's no need to apologize, we appreciate the heads-up and your contributions to the project thus far.

All the best for your exams!

**Comment by rmondal-official** [comment]
Hello @Madanraj0519 , thanks for your interest in contributing! I've assigned the issue to you.

**Comment by RajeshTechForge** [comment]
Hello,

As we prepare for the exciting transition to **PINAC-Workspace 2.0**, we want to ensure a smooth and focused development process. In light of this, we will be closing this issue as part of our efforts to streamline our project management.

We greatly appreciate the contributions and discussions that have taken place here. Your insights and input have been invaluable, and we encourage you to bring your ideas and enthusiasm to **PINAC-Workspace 2.0** where we will continue to collaborate and innovate together.

Thank you for your understanding and support as we move forward into this new era of our project.

Best regards,
**The PINAC-Workspace Team**
